import { Template } from "@/types/card";

export const templates: Template[] = [
  {
    id: "corporate-blue",
    name: "Corporate Blue",
    category: "Corporate",
    description: "Professional blue-accented card, perfect for business executives.",
    isPremium: false,
    isDoubleSided: true,
    tags: ["professional", "blue", "corporate"],
    previewBg: "from-blue-600 to-blue-800",
    defaultColors: {
      primary: "#2563EB",
      secondary: "#1E3A8A",
      accent: "#60A5FA",
    },
    defaultFont: "Inter",
  },
  {
    id: "minimal-white",
    name: "Minimal White",
    category: "Minimal",
    description: "Ultra-clean design with elegant typography and generous whitespace.",
    isPremium: false,
    isDoubleSided: false,
    tags: ["minimal", "clean", "elegant"],
    previewBg: "from-gray-100 to-gray-200",
    defaultColors: {
      primary: "#0F172A",
      secondary: "#475569",
      accent: "#3B82F6",
    },
    defaultFont: "Plus Jakarta Sans",
  },
  {
    id: "dark-luxury",
    name: "Dark Luxury",
    category: "Luxury",
    description: "Premium dark card with gold accents. Exudes sophistication.",
    isPremium: true,
    isDoubleSided: true,
    tags: ["luxury", "dark", "gold", "premium"],
    previewBg: "from-gray-900 to-gray-800",
    defaultColors: {
      primary: "#D4AF37",
      secondary: "#1A1A2E",
      accent: "#C9A227",
    },
    defaultFont: "Montserrat",
  },
  {
    id: "tech-modern",
    name: "Tech Modern",
    category: "Technology",
    description: "Sleek dark design with gradient accents for tech professionals.",
    isPremium: false,
    isDoubleSided: true,
    tags: ["tech", "dark", "modern", "startup"],
    previewBg: "from-slate-900 to-violet-900",
    defaultColors: {
      primary: "#8B5CF6",
      secondary: "#0F172A",
      accent: "#06B6D4",
    },
    defaultFont: "Manrope",
  },
  {
    id: "finance-gold",
    name: "Finance Gold",
    category: "Finance",
    description: "Conservative navy and gold — trusted by financial professionals.",
    isPremium: true,
    isDoubleSided: true,
    tags: ["finance", "navy", "gold", "professional"],
    previewBg: "from-slate-800 to-slate-900",
    defaultColors: {
      primary: "#B8972A",
      secondary: "#0C1B33",
      accent: "#E8C547",
    },
    defaultFont: "Poppins",
  },
  {
    id: "medical-clean",
    name: "Medical Clean",
    category: "Medical",
    description: "Clean, trustworthy design for healthcare professionals.",
    isPremium: false,
    isDoubleSided: false,
    tags: ["medical", "clean", "blue", "health"],
    previewBg: "from-cyan-500 to-blue-600",
    defaultColors: {
      primary: "#0077CC",
      secondary: "#E8F4FD",
      accent: "#00A9A5",
    },
    defaultFont: "Roboto",
  },
  {
    id: "real-estate",
    name: "Real Estate",
    category: "Real Estate",
    description: "Warm, premium card design for real estate agents.",
    isPremium: false,
    isDoubleSided: true,
    tags: ["real estate", "warm", "premium"],
    previewBg: "from-amber-700 to-amber-900",
    defaultColors: {
      primary: "#92400E",
      secondary: "#FFFBEB",
      accent: "#D97706",
    },
    defaultFont: "Poppins",
  },
  {
    id: "creative-color",
    name: "Creative Vibrant",
    category: "Creative",
    description: "Bold, colorful design with geometric shapes for creative professionals.",
    isPremium: false,
    isDoubleSided: true,
    tags: ["creative", "colorful", "geometric", "bold"],
    previewBg: "from-pink-500 to-violet-600",
    defaultColors: {
      primary: "#EC4899",
      secondary: "#7C3AED",
      accent: "#F59E0B",
    },
    defaultFont: "DM Sans",
  },
  {
    id: "bold-chevron",
    name: "Bold Chevron",
    category: "Corporate",
    description: "Clean cream background with a bold red chevron accent — inspired by modern corporate card design.",
    isPremium: false,
    isDoubleSided: true,
    tags: ["corporate", "chevron", "modern", "clean"],
    previewBg: "from-red-500 to-red-700",
    defaultColors: {
      primary: "#E5362A",
      secondary: "#1B2B5E",
      accent: "#E5362A",
    },
    defaultFont: "Inter",
  },
  {
    id: "rdash-pro",
    name: "RDash Pro",
    category: "Corporate",
    description: "Split-panel card with white left panel for contact details and a dark accent right panel for branding and QR. Faithful to the RDash business card design.",
    isPremium: false,
    isDoubleSided: true,
    tags: ["corporate", "split", "professional", "rdash", "modern"],
    previewBg: "from-red-600 to-slate-700",
    defaultColors: {
      primary: "#E21F26",
      secondary: "#354054",
      accent: "#E21F26",
    },
    defaultFont: "Inter",
  },
  {
    id: "custom-upload",
    name: "Custom Upload",
    category: "All",
    description: "Upload your own business card design — front and back — as any image format.",
    isPremium: false,
    isDoubleSided: true,
    tags: ["custom", "upload", "blank"],
    previewBg: "from-slate-100 to-slate-200",
    defaultColors: {
      primary: "#3B82F6",
      secondary: "#1E293B",
      accent: "#06B6D4",
    },
    defaultFont: "Inter",
  },
];

export const getTemplate = (id: string): Template | undefined =>
  templates.find((t) => t.id === id);

export const defaultCardData = (template: Template) => ({
  fullName: "Alex Johnson",
  designation: "Senior Product Designer",
  company: "Innovate Studio",
  phone: "+1 (555) 123-4567",
  mobile: "+1 (555) 987-6543",
  email: "alex@innovatestudio.com",
  website: "www.innovatestudio.com",
  address: "123 Design Street, San Francisco, CA 94105",
  slogan: "",
  linkedin: "linkedin.com/in/alexjohnson",
  instagram: "@alexjohnson",
  facebook: "",
  twitter: "@alexjohnson",
  youtube: "",
  primaryColor: template.defaultColors.primary,
  secondaryColor: template.defaultColors.secondary,
  accentColor: template.defaultColors.accent,
  fontFamily: template.defaultFont,
  fontSizeName: 100,
  fontSizeTitle: 100,
  fontSizeDetails: 100,
  fontSizeDesignation: 100,
  fontSizeSlogan: 100,
  fontSizeEmail: 100,
  fontSizePhone: 100,
  fontSizeAddress: 100,
  fontSizeCompany: 100,
  fontSizeWebsite: 100,
  logoUrl: null,
  logoUrlFront: null,
  logoUrlBack: null,
  logoSizeFront: 100,
  logoSizeBack: 100,
  logoText: "IS",
  customFrontImage: null,
  customBackImage: null,
  showQR: true,
  qrCodeType: "website" as const,
  qrCodeValue: "www.innovatestudio.com",
  backgroundType: "solid" as const,
  backgroundColor: "#ffffff",
  cardSize: "us" as const,
  isDoubleSided: template.isDoubleSided,
});
